# Generated by Django 6.0.1 on 2026-01-21 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(blank=True, max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=80)),
                ('manufacture_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('model_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plate', models.CharField(blank=True, max_length=10)),
                ('fuel_type', models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('diesel', 'Diesel'), ('gnv', 'GNV'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido'), ('flex', 'Flex')], default='gasolina', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField()),
                ('odometer_km', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('diesel', 'Diesel'), ('gnv', 'GNV'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido'), ('flex', 'Flex')], max_length=16)),
                ('liters', models.DecimalField(decimal_places=3, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_full_tank', models.BooleanField(default=True)),
                ('station_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuelings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuelings', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=~models.Q(('plate', '')), fields=('owner', 'plate'), name='uq_vehicle_owner_plate'),
        ),
        migrations.AddIndex(
            model_name='fueling',
            index=models.Index(fields=['owner', 'vehicle', '-occurred_at'], name='vehicles_fu_owner_i_6f0b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='fueling',
            index=models.Index(fields=['owner', 'vehicle', '-odometer_km'], name='vehicles_fu_owner_i_d7c407_idx'),
        ),
        migrations.AddConstraint(
            model_name='fueling',
            constraint=models.CheckConstraint(condition=models.Q(('liters__gt', 0)), name='ck_fueling_liters_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='fueling',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gt', 0)), name='ck_fueling_cost_gt_0'),
        ),
    ]
