# Generated by Django 5.2.10 on 2026-01-25 16:37

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_brands(apps, schema_editor):
    StationBrand = apps.get_model("vehicles", "StationBrand")

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, brand FROM vehicles_station")
        station_rows = cursor.fetchall()

    for _, brand_value in station_rows:
        clean = (brand_value or "").strip()
        if not clean:
            continue
        StationBrand.objects.get_or_create(name=clean)

    schema_editor.execute("ALTER TABLE vehicles_station RENAME COLUMN brand TO brand_name")
    schema_editor.execute("ALTER TABLE vehicles_station ADD COLUMN brand_id bigint")

    for station_id, brand_value in station_rows:
        clean = (brand_value or "").strip()
        if not clean:
            continue
        brand = StationBrand.objects.filter(name=clean).first()
        if brand:
            schema_editor.execute(
                "UPDATE vehicles_station SET brand_id = %s WHERE id = %s",
                [brand.id, station_id],
            )


def backwards_copy_brands(apps, schema_editor):
    StationBrand = apps.get_model("vehicles", "StationBrand")

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, brand_id FROM vehicles_station")
        station_rows = cursor.fetchall()

    schema_editor.execute("ALTER TABLE vehicles_station RENAME COLUMN brand_name TO brand")

    for station_id, brand_id in station_rows:
        if not brand_id:
            continue
        brand = StationBrand.objects.filter(id=brand_id).first()
        if brand:
            schema_editor.execute(
                "UPDATE vehicles_station SET brand = %s WHERE id = %s",
                [brand.name, station_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_station_fueling_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Station brand',
                'verbose_name_plural': 'Station brands',
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(forwards_copy_brands, backwards_copy_brands),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='station',
                    name='brand',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='stations',
                        to='vehicles.stationbrand',
                    ),
                ),
            ],
        ),
    ]
