# Generated by Django 5.2.10 on 2026-02-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_stationbrand_alter_station_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueling',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
